// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDuNLO-v5axDYTcKCQzLaMVvxV85ocFnU',
    appId: '1:452046785925:web:f8fe8a5f17f7da8a2208ec',
    messagingSenderId: '452046785925',
    projectId: 'my-weather-2e1fd',
    authDomain: 'my-weather-2e1fd.firebaseapp.com',
    storageBucket: 'my-weather-2e1fd.appspot.com',
    measurementId: 'G-XNR3FDMN69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpICjPTZ5ruNPCbiRU33S0yWkm187xhR4',
    appId: '1:452046785925:android:2b77a4ed7e8ffbc82208ec',
    messagingSenderId: '452046785925',
    projectId: 'my-weather-2e1fd',
    storageBucket: 'my-weather-2e1fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn1t0xIfPq20jHs5k2Lup8WyZs0JgtAwE',
    appId: '1:452046785925:ios:be5e5399ce493f432208ec',
    messagingSenderId: '452046785925',
    projectId: 'my-weather-2e1fd',
    storageBucket: 'my-weather-2e1fd.appspot.com',
    iosClientId: '452046785925-o2jom5fik8i9gq3drnjgu8c5vha16852.apps.googleusercontent.com',
    iosBundleId: 'com.example.sartUpProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn1t0xIfPq20jHs5k2Lup8WyZs0JgtAwE',
    appId: '1:452046785925:ios:be5e5399ce493f432208ec',
    messagingSenderId: '452046785925',
    projectId: 'my-weather-2e1fd',
    storageBucket: 'my-weather-2e1fd.appspot.com',
    iosClientId: '452046785925-o2jom5fik8i9gq3drnjgu8c5vha16852.apps.googleusercontent.com',
    iosBundleId: 'com.example.sartUpProject',
  );
}
